---
title: "netCDF"
author: "Jessica Ernakovich"
date: "1/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ncdf4)
library(ggplot2)
library(dplyr)
library(tidyr)
```

# read in data from a file

```{r}
nc <- nc_open("data/WG2013CTD.nc")
```

```{r}
print(nc)
```

```{r}
vars <- attributes(nc$var)$names
vars # this allows you to see what all the variables are
```

```{r}
dims <- attributes(nc$dim)$names
dims
```


```{r}
salinity <- ncvar_get(nc, "sal")
time <- ncvar_get(nc, "time")
depth <-ncvar_get(nc, "z")
```

# reformat the output  
we want to move this from matrix to dataframe so we can use ggplot and also because the matrix is non-uniform (not regularly gridded (i.e. not the same spacing on the axes for lat long))


matlab time to R 
```{r}
time <- as.POSIXct((time + 719529)*86400, origin = "1970-01-01", tz = "UTC")
```

new object called salinity_data
```{r}
salinity_data <- as.data.frame(salinity)
```

assign column names to depth values
```{r}
names(salinity_data) <- as.character(depth)
```

reshape the data and add time

```{r}
salinity_data_long <- salinity_data %>% 
  mutate(time = time) %>% # adding time column onto the salinity data.frame that was coerced from the matrix
  gather(key = "depth", value = "salinity", -time) %>% #make the dataframe long and don't gather, but rather repopulate time
  mutate(depth = as.numeric(depth)) #coerce depth column to be a number rather than a character

head(salinity_data_long)
```


# plots

```{r}
ggplot(salinity_data_long, mapping = aes(x = time, y = depth, fill = salinity)) + geom_raster()
```


```{r}
ggplot(salinity_data_long, mapping = aes(x = salinity, 
                                         y = depth, 
                                         color = time)) + 
  geom_line(size = 0.1) + 
  scale_y_reverse()
```






