---
title: "ROpenSci demo"
author: "Jessica Ernakovich"
date: "1/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## `rnoaa` package

```{r, eval = F}
install.packages("rnoaa")
install.packages("ncdf4")
```

```{r}
library(rnoaa)
library(ncdf4)
library(ggplot2)
```

note: Janette says to use the vignettes to train yourself


read in buoy data
```{r}
bd <- buoy(dataset = "cwind", buoyid = 46080, year = 2018, datatype = "c")
```

```{r}
wind_speed <- data.frame(time = strptime(bd$data$time, format = "%Y-%m-%dT%TZ"), speed = bd$data$wind_spd) #as.POSIXct coerces the time to be in R date time type, because it was coming up as a factor, but it didn't work here because the time was strange 
# learned later that we can use striptime
```

```{r}
ggplot(wind_speed, aes(x = time, y = speed)) +
  geom_point()
```



# `mapr` package

```{r, eval = F}
install.packages("mapr", dependencies = TRUE)
```

```{r}
library(mapr)
library(spocc)
```

Plot locations of GBIF species offurrence dta for grizzly and polar bears

```{r}
spp <- c("Ursus arctos", "Ursus maritimus", "Ursus americanus kermodei")
bears <- occ(query = spp, 
             from = "gbif", 
             has_coords = T, 
             limit = 500)
```

```{r}
map_leaflet(bears, color = c("black", "gray", "pink"), size = 1)
```

```{r}
spirit_bears <- bears$gbif$data$Ursus_americanus_kermodei
```

